laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/**
 * Model Repositories Binding
 */
App::bind('ProjetoFoto\ProjetoFotoRepositoryInterface', 'ProjetoFoto\ProjetoFoto');

/**
 * Rotas de autenticação
 */
Route::get('painel/logout',  array('as' => 'painel.logout',      'uses' => 'App\Controllers\Painel\AuthController@getLogout'));
Route::get('painel/login',   array('as' => 'painel.login',       'uses' => 'App\Controllers\Painel\AuthController@getLogin'));
Route::post('painel/login',  array('as' => 'painel.login.post',  'uses' => 'App\Controllers\Painel\AuthController@postLogin'));
Route::resource('groups', 'App\Controllers\Painel\GroupController');


/**
 * Rotas do painel
 */
Route::group(array('prefix' => 'painel', 'before' => 'auth.admin'), function() {
    Route::any('/', 'App\Controllers\Painel\PaginasController@index');
    Route::resource('paginas', 'App\Controllers\Painel\PaginasController');
    Route::resource('categorias', 'App\Controllers\Painel\CategoriasController');
    Route::resource('projetos', 'App\Controllers\Painel\ProjetosController');
    Route::resource('midias', 'App\Controllers\Painel\MidiasController');
    Route::resource('users', 'App\Controllers\Painel\UsersController');
    Route::resource('socials', 'App\Controllers\Painel\SocialsController');
    Route::resource('slides', 'App\Controllers\Painel\SlidesController');
    Route::resource('locais', 'App\Controllers\Painel\LocalsController');
    Route::resource('profissionais', 'App\Controllers\Painel\ProfissionalsController');

    //Ordenamento de ítens
    Route::post('ordenar', 'App\Controllers\Painel\OrdenadorController@ordenar');

    //Upload de fotos em projetos
    Route::resource('projetofotos', 'App\Controllers\Painel\ProjetoFotosController');
    //Upload de fotos em mídias
    Route::resource('midiafotos', 'App\Controllers\Painel\MidiaFotosController');
});

/**
 * Rota da home
 */
Route::get('/', function(){
    //$slides = Cache::get('slides');
    $slides = Slide::ordered()->get();

    //$destaques = Cache::get('projetosDestacados')->toArray();
    $destaques = Projeto::where('destaque', true)->ordered()->with('categoria')->get()->toArray();
    $k = array_rand($destaques);
    $destaque = $destaques[$k];

    return View::make('site.home.index', compact('slides', 'destaque'));
});

/**
 * Rotas do front-end
 */

/**
 * Empresa (view por rota)
 */
Route::get('empresa', function(){
    $empresa = Pagina::where('slug', 'empresa')->first();

    return View::make('site.empresa', compact('empresa'));
});

/**
 * Projetos (view por controller)
 */
Route::get('projetos', 'App\Controllers\Site\ProjetosController@categorias');
Route::get('projetos/{categoria_slug}',
        array('as' => 'projetos', 'uses' => 'App\Controllers\Site\ProjetosController@categoria'));
Route::get('projetos/{categoria_slug}/{projeto_slug}',
        array('as' => 'projeto', 'uses' => 'App\Controllers\Site\ProjetosController@projeto'));

/**
 * Publicações (view por rota)
 */
Route::get('publicacoes', function(){
    $publicacoes = Midia::all();

    return View::make('site.publicacoes', compact('publicacoes'));
});

/**
 * Profissionais (view por controller / ajax post)
 */
Route::get('profissionais', 'App\Controllers\Site\ProfissionaisController@index');
Route::post('profissionais', 'App\Controllers\Painel\ProfissionalsController@store');

/**
 * Contato (view por controller / ajax post)
 */
Route::get('contato', 'App\Controllers\Site\ContatoController@index');
Route::post('contato', 'App\Controllers\Site\ContatoController@sendMail');

/**
 * Envio de currículos
 */
Route::post('curriculos', 'App\Controllers\Site\ContatoController@curriculos');

/**
 * Composers
 */
View::composer('site.layout.default', 'App\Composers\ContactsComposer');
View::composer('site.layout.default', 'App\Composers\SocialsComposer');
View::composer('site.layout.default', 'App\Composers\CategoriasComposer');

Route::get('teste', 'App\Controllers\Painel\ProjetoFotosController@index');

laravel/app/controllers/painel/AuthController.php
<?php namespace App\Controllers\Painel;

    use Auth, BaseController, Form, Input, Redirect, Sentry, View;

    class AuthController extends BaseController
    {
        public function getLogin()
        {
            return View::make('painel.auth.login');
        }

        public function postLogin()
        {
            $credentials = array(
                'username'    => Input::get('username'),
                'password' => Input::get('password')
            );

            try {
                $user = Sentry::authenticate($credentials, false);

                if ($user) {
                    return Redirect::route('painel.paginas.index');
                }
            } catch (\Exception $e) {
                return Redirect::route('painel.login')->withErrors(array('login' => $e->getMessage()));
            }
        }

        public function getLogout()
        {
            Sentry::logout();

            return Redirect::route('painel.login');
        }

    }

laravel/app/controllers/painel/CategoriasController.php
<?php namespace App\Controllers\Painel;

use Auth, BaseController, Form, Input, Redirect, Sentry, View,
    Validator, Categoria, Image;

class CategoriasController extends BaseController
{
    /**
     * Categoria Repository
     *
     * @var Categoria
     */
    protected $categoria;

    public function __construct(Categoria $categoria)
    {
        $this->categoria = $categoria;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $categorias = $this->categoria->ordered()->get();

        return View::make('painel.categorias.index', compact('categorias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('painel.categorias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = Input::all();
        $input['user_id'] = Sentry::getUser()->id;
        $validation = Validator::make($input, Categoria::$rules);

        if ($validation->passes()) {
            if (Input::hasFile('imagem')) {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'categorias');
            }
            $this->categoria->create($input);

            return Redirect::route('painel.categorias.index');
        }

        return Redirect::route('painel.categorias.create')
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function show($id)
    {
        $categoria = $this->categoria->findOrFail($id);

        return View::make('painel.categorias.show', compact('categoria'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function edit($id)
    {
        $categoria = $this->categoria->find($id);

        if (is_null($categoria)) {
            return Redirect::route('painel.categorias.index');
        }

        return View::make('painel.categorias.edit', compact('categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function update($id)
    {
        $input = array_except(Input::all(), array('_method', 'imagem'));
        $input['user_id'] = Sentry::getUser()->id;

        $validation = Validator::make($input, Categoria::$rules);

        if ($validation->passes()) {
            $categoria = $this->categoria->find($id);

            if (Input::hasFile('imagem')) {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'categorias');
                @unlink(public_path(substr($categoria->imagem, 1)));
            }

            $categoria->update($input);

            return Redirect::route('painel.categorias.show', $id);
        }

        return Redirect::route('painel.categorias.edit', $id)
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function destroy($id)
    {
        $categoria = $this->categoria->find($id);

        @unlink(public_path(substr($categoria->imagem, 1)));

        $categoria->delete();

        return Redirect::route('painel.categorias.index');
    }

}

laravel/app/controllers/painel/LocalsController.php
<?php namespace App\Controllers\Painel;

use Auth, BaseController, Form, Input, Redirect, Sentry, View,
    Validator, Local, Image;

class LocalsController extends BaseController
{
    /**
     * Local Repository
     *
     * @var Local
     */
    protected $local;

    public function __construct(Local $local)
    {
        $this->local = $local;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $locals = $this->local->ordered()->get();

        return View::make('painel.locais.index', compact('locals'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('painel.locais.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = Input::all();
        $validation = Validator::make($input, Local::$rules);

        if ($validation->passes()) {
            if (Input::hasFile('imagem')) {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'locais');
            }
            $this->local->create($input);

            return Redirect::route('painel.locais.index');
        }

        return Redirect::route('painel.locais.create')
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function show($id)
    {
        $local = $this->local->findOrFail($id);

        return View::make('painel.locais.show', compact('local'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function edit($id)
    {
        $local = $this->local->find($id);

        if (is_null($local)) {
            return Redirect::route('painel.locais.index');
        }

        return View::make('painel.locais.edit', compact('local'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function update($id)
    {
        $input = array_except(Input::all(), array('_method', 'imagem'));
        $validation = Validator::make($input, Local::$rules);

        if ($validation->passes()) {
            $local = $this->local->find($id);

            if (Input::hasFile('imagem')) {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'locais');
                @unlink(public_path(substr($local->imagem, 1)));
            }

            $local->update($input);

            return Redirect::route('painel.locais.edit', $id);
        }

        return Redirect::route('painel.locais.edit', $id)
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function destroy($id)
    {
        $local = $this->local->find($id);

        @unlink(public_path(substr($local->imagem, 1)));

        $local->delete();

        return Redirect::route('painel.locais.index');
    }

}

laravel/app/controllers/painel/MidiaFotosController.php
<?php namespace App\Controllers\Painel;

use App\Controllers\Painel\RelatedUploadController;
use MidiaFoto;

class MidiaFotosController extends RelatedUploadController
{

    /**
     * MidiaFotos constructor
     *
     * @param ProjetoFoto $midiaFoto Instância do repositório MidiaFoto
     */
    public function __construct(Midiafoto $midiaFoto)
    {
        parent::__construct($midiaFoto);
    }

}

laravel/app/controllers/painel/MidiasController.php
<?php namespace App\Controllers\Painel;

use Auth, BaseController, Form, Input, Redirect, Sentry, View,
    Validator, Categoria, Image, Midia;

class MidiasController extends BaseController
{
    /**
     * Categoria Repository
     *
     * @var Categoria
     */
    protected $midia;

    public function __construct(Midia $midia)
    {
        $this->midia = $midia;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $midias = $this->midia->ordered()->get();

        return View::make('painel.midias.index', compact('midias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //Array com categorias disponíveis e seus respectivos ids como chave.
        $categorias = array('' => 'Selecione uma categoria') + Categoria::lists('titulo', 'id');

        return View::make('painel.midias.create', compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = array_except(Input::all(), array('_method', 'midia_id'));;
        $input['user_id'] = Sentry::getUser()->id;
        $validation = Validator::make($input, Midia::$rules);

        if ($validation->passes()) {
            if (Input::hasFile('imagem')) {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'midias/destaque');
            }

            $midia = new Midia($input);
            $midia->save();

            return Redirect::route('painel.midias.edit', $midia->id);
        }

        return Redirect::route('painel.midias.create')
            ->withInput()
            ->withErrors($validation);
    }

    /**
     * Display the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function show($id)
    {
        $midia = $this->midia->findOrFail($id);

        return View::make('painel.midias.show', compact('midia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function edit($id)
    {
        $midia = $this->midia->find($id);

        if (is_null($midia)) {
            return Redirect::route('painel.midias.index');
        }

        return View::make('painel.midias.edit', compact('midia', 'categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function update($id)
    {
        $input = array_except(Input::all(), array('_method', 'imagem', 'object_id'));
        $input['user_id'] = Sentry::getUser()->id;

        $validation = Validator::make($input, Midia::$rules);

        if ($validation->passes()) {
            $midia = $this->midia->find($id);

             if (Input::hasFile('imagem')) {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'midias/destaque');
                @unlink(public_path(substr($projeto->imagem, 1)));
            }

            $midia->update($input);

            return Redirect::route('painel.midias.show', $id);
        }

        return Redirect::route('painel.midias.edit', $id)
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function destroy($id)
    {
        $midia = $this->midia->find($id);

        @unlink(public_path(substr($midia->imagem, 1)));

        $midia->delete();

        return Redirect::route('painel.midias.index');
    }

}

laravel/app/controllers/painel/OrdenadorController.php
<?php namespace App\Controllers\Painel;

class OrdenadorController extends \BaseController
{
    public function ordenar()
    {
        $input = \Input::all();
        $model = $input['model'];
        $modelUcf = ucfirst($model);

        parse_str($input['itens'], $itens);

        $result = null;
        foreach ($itens[$model] as $key => $value) {
            $object = $modelUcf::find($value);
            $object->ordem = $key;
            $object->save();
        }

        return \Response::json(
                    array(
                        'error' 	=> 	false,
                        'message' 	=>	'Ítens ordenados com sucesso'
                    ), 200
                );

    }
}

laravel/app/views/painel/_layouts/default.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Hi-Spada</title>

    <link href="{{ URL::asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/css/bootstrap-responsive.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/css/jasny-bootstrap.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/css/jasny-bootstrap-responsive.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/black-tie/jquery-ui.min.css">
    <style>
        body{
            padding-top: 60px;
        }
        .control-group{
            max-width:600px;
        }
    </style>
</head>
<body>
<div>
    @if (Sentry::check())
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="{{ URL::to('/') }}">Hi-Spada</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="{{ Request::is('*paginas*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.paginas.index')}}">Paginas</a></li>
                        <li class="{{ Request::is('*categorias*') || Request::is('*projetos*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.categorias.index')}}">Projetos</a></li>
                        <li class="{{ Request::is('*midias*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.midias.index')}}">Publicações</a></li>
                        <li class="{{ Request::is('*profissionais*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.profissionais.index')}}">Profissionais</a></li>
                        <li class="{{ Request::is('*socials*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.socials.index')}}">Redes Sociais</a></li>
                        <li class="{{ Request::is('*slides*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.slides.index')}}">Slides</a></li>
                        <li class="{{ Request::is('*locais*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.locais.edit', 1)}}">Contato</a></li>
                        <li class="{{ Request::is('*users*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.users.index')}}">Usuários</a></li>
                    </ul>
                    <ul class="nav pull-right">
                        <li>
                            <a href="{{ URL::route('painel.logout') }}" class="pull-right">Logout</a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
    @endif

    <div class="container">
            @if (Session::has('message'))
                <div class="flash alert">
                    <p>{{ Session::get('message') }}</p>
                </div>
            @endif

            @yield('main')
        </div>
</div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ URL::asset('assets/js/vendor/jquery-1.9.1.min.js') }}"><\/script>')</script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="{{ URL::asset('assets/js/bootstrap.min.js' )}}"></script>
    <script src="{{ URL::asset('assets/js/jasny-bootstrap.min.js' )}}"></script>
    <script src="{{ URL::asset('assets/ckeditor/ckeditor.js' )}}"></script>
    <script src="{{ URL::asset('assets/ckeditor/adapters/jquery.js' )}}"></script>
    <script src="{{ URL::asset('assets/js/plugins.js' )}}"></script>
    <script src="{{ URL::asset('assets/js/admin1.js' )}}"></script>
    <script>
        function string_to_slug(str)
        {
          str = str.replace(/^\s+|\s+$/g, ''); // trim
          str = str.toLowerCase();

          // remove accents, swap ñ for n, etc
          var from = "ãàáäâèéëêìíïîõòóöôùúüûñç·/_,:;";
          var to   = "aaaaaeeeeiiiiooooouuuunc------";
          for (var i=0, l=from.length ; i<l ; i++) {
            str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
          }

          str = str.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
            .replace(/\s+/g, '-') // collapse whitespace and replace by -
            .replace(/-+/g, '-'); // collapse dashes

          return str;
        }

        var title = $('#titulo'),
        slug = $('#slug');

        title.on('keyup', function() {
          var val = $(this).val();
          val = string_to_slug(val);
          slug.val(val);
        });

    </script>
</body>
</html>